=== leerzeichen7/nice/assets/credits.dtd
<!ELEMENT Credits (Credit*)>
<!ELEMENT Credit (Picture | Video)>
<!ELEMENT Picture (Title, Source)>
<!ELEMENT Video (Title, Source)>
<!ELEMENT Titel (#PCDATA)>
<!ELEMENT Source (#PCDATA)>

=== leerzeichen7/nice/assets/credits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE credit SYSTEM "credits.dtd">

<Credits>
    <!-- Arcane -->
    <Credit>
        <Picture>
            <Titel>Arcane Logo</Titel>
            <Source>https://commons.wikimedia.org/wiki/File:Arcane_Title_Text.png</Source>
        </Picture>
    </Credit>
    <!-- Loki -->   
    <Credit>
        <Picture>
            <Titel>Loki Logo</Titel>
            <Source>https://commons.wikimedia.org/wiki/File:Loki_TV_Series_Logo_Black.svg</Source>
        </Picture>
    </Credit>
    <!-- WandaVision -->
    <Credit>
        <Picture>
            <Titel>WandaVision Logo</Titel>
            <Source>https://commons.wikimedia.org/wiki/File:WandaVision_wordmark_logo.svg</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>WandaVision Poster</Titel>
            <Source>https://images.app.goo.gl/wz8PS1tTy73bLLHJ7</Source>
        </Picture>
    </Credit>
    <!-- Falcon and WinterSoldier -->   
    <Credit>
        <Picture>
            <Titel>Loki Logo</Titel>
            <Source>https://upload.wikimedia.org/wikipedia/en/9/9a/The_Falcon_and_the_Winter_Soldier_logo.png</Source>
        </Picture>
    </Credit>
    
    <!-- TRAILERS -->
    <!-- Arcane Trailer -->
    <Credit>
        <Video>
            <Titel>Arcane | Final Trailer | Netflix</Titel>
            <Source>https://youtu.be/3Svs_hl897c</Source>
        </Video>
    </Credit>
    <!-- Loki Trailer -->
    <Credit>
        <Video>
            <Titel>Marvel Studios' Loki | Official Trailer | Disney+</Titel>
            <Source>https://youtu.be/nW948Va-l10</Source>
        </Video>
    </Credit>
    <!-- WandaVision Trailer -->
    <Credit>
        <Video>
            <Titel>WandaVision | Official Trailer | Disney+</Titel>
            <Source>https://youtu.be/sj9J2ecsSpo</Source>
        </Video>
    </Credit>
    <!-- Falcon and WinterSoldier Trailer -->
    <Credit>
        <Video>
            <Titel>Official Trailer | The Falcon and the Winter Soldier | Disney+</Titel>
            <Source>https://youtu.be/IWBsDaFWyTE</Source>
        </Video>
    </Credit>
</Credits>

=== leerzeichen7/nice/assignment-2a/website-content/credits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE credit SYSTEM "credits.dtd">

<Credits>
    <!-- Arcane -->
    <Credit>
        <Picture>
            <Titel>Arcane Logo</Titel>
            <Source>https://commons.wikimedia.org/wiki/File:Arcane_Title_Text.png</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>Arcane Poster</Titel>
            <Source>https://static.kino.de/wp-content/uploads/2021/05/Arcane-Poster-221.jpg</Source>
        </Picture>
    </Credit>
    <!-- Loki -->   
    <Credit>
        <Picture>
            <Titel>Loki Logo</Titel>
            <Source>https://commons.wikimedia.org/wiki/File:Loki_TV_Series_Logo_Black.svg</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>Loki Poster</Titel>
            <Source>https://de.web.img3.acsta.net/pictures/21/03/19/08/19/3635237.jpg</Source>
        </Picture>
    </Credit>
    <!-- WandaVision -->
    <Credit>
        <Picture>
            <Titel>WandaVision Logo</Titel>
            <Source>https://commons.wikimedia.org/wiki/File:WandaVision_wordmark_logo.svg</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>WandaVision Poster</Titel>
            <Source>https://medienjournal-blog.de/wp-content/uploads/2021/03/wandavision-cover.jpg</Source>
        </Picture>
    </Credit>
    <!-- Falcon and WinterSoldier -->   
    <Credit>
        <Picture>
            <Titel>Falcon and WinterSoldier Logo</Titel>
            <Source>https://upload.wikimedia.org/wikipedia/en/9/9a/The_Falcon_and_the_Winter_Soldier_logo.png</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>Falcon and WinterSoldier Poster</Titel>
            <Source>https://de.web.img3.acsta.net/r_1920_1080/pictures/21/02/08/08/30/3306240.jpg</Source>
        </Picture>
    </Credit>
    <!-- Marvel Info Page -->   
    <Credit>
        <Picture>
            <Titel>Marvel Cinamatic Universe Timeline</Titel>
            <Source>https://www.cnet.com/a/img/i35br6NbWUsLGnyY_52b_OO-c24=/2019/03/27/63aa717b-53b9-4cac-8805-17335fc4ffc5/mcu-timeline-2019-redesign-v47-large.jpg</Source>
        </Picture>
    </Credit>
    <!-- Riot Info Page -->
    <Credit>
        <Picture>
            <Titel>WildRift Logo</Titel>
            <Source>https://images-ext-1.discordapp.net/external/nhi8rlWEyXYrVXTv5EsAJfP7ik59MgH7mW5IrA2usps/https/play-lh.googleusercontent.com/JQgpYrll8DZ8o_9kb1SD89zDOcPNMVbJtpjeWf861BIzfvB1I9bBLWiPQz_Kum8lWD4</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>Team Fight Tactics Logo</Titel>
            <Source>https://static.wikia.nocookie.net/leagueoflegends/images/5/5f/Teamfight_Tactics_navigation.png/revision/latest/scale-to-width-down/460?cb=20191017052258</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>League of Legends Logo</Titel>
            <Source>https://static.wikia.nocookie.net/leagueoflegends/images/e/e6/League_of_Legends_navigation.png/revision/latest/scale-to-width-down/460?cb=20191019142012</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>Legends of Runeterra Logo</Titel>
            <Source>https://static.wikia.nocookie.net/leagueoflegends/images/e/eb/Legends_of_Runeterra_navigation.png/revision/latest/scale-to-width-down/460?cb=20191017052300</Source>
        </Picture>
    </Credit>
    <Credit>
        <Picture>
            <Titel>Runeterra Map</Titel>
            <Source>https://images-ext-1.discordapp.net/external/ZPWKLkCzJZp0NX_OKZRAq7FMN3OibOihPuZIvgi97c8/https/cdn.vox-cdn.com/thumbor/FaHaLlrdMRDEhpxYBSxhJ4b1Fm8%3D/0x2%3A1775x931/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/11737195/chrome_2018_07_24_11_40_50.jpg</Source>
        </Picture>
    </Credit>
    <!-- TRAILERS -->
    <!-- Arcane Trailer -->
    <Credit>
        <Video>
            <Titel>Arcane | Final Trailer | Netflix</Titel>
            <Source>https://youtu.be/3Svs_hl897c</Source>
        </Video>
    </Credit>
    <!-- Loki Trailer -->
    <Credit>
        <Video>
            <Titel>Marvel Studios' Loki | Official Trailer | Disney+</Titel>
            <Source>https://youtu.be/nW948Va-l10</Source>
        </Video>
    </Credit>
    <!-- WandaVision Trailer -->
    <Credit>
        <Video>
            <Titel>WandaVision | Official Trailer | Disney+</Titel>
            <Source>https://youtu.be/sj9J2ecsSpo</Source>
        </Video>
    </Credit>
    <!-- Falcon and WinterSoldier Trailer -->
    <Credit>
        <Video>
            <Titel>Official Trailer | The Falcon and the Winter Soldier | Disney+</Titel>
            <Source>https://youtu.be/IWBsDaFWyTE</Source>
        </Video>
    </Credit>
</Credits>
